project:
  name: evadiab-clinical-ml
  run_name: kaggle_cardio_mlp_baseline
  seed: 42

data:
  raw_csv_path: data/raw/kaggle_cardio/cardio_train.csv
  sep: ";"              # Kaggle cardio is typically ';'
  target_col: cardio
  id_col: id

split:
  test_size: 0.2
  stratify: true

train:
  epochs: 20
  batch_size: 512
  lr: 1e-3
  weight_decay: 1e-4
  num_workers: 2
  device: auto          # auto | cpu | cuda

model:
  hidden_dims: [128, 64]
  dropout: 0.2

wandb:
  enabled: true
  log_every_steps: 20
